bs_result_get:
    path:    /Result/Get
    defaults:
        _controller:    BSResultBundle:Result:get

bs_result_offer_to_result:
    path:    /Offer/To/Result
    defaults:
        _controller:    BSResultBundle:Result:offerToResult

bs_result_delete_duplicate_result:
    path:    /Result/Delete/Duplicate
    defaults:
        _controller:    BSResultBundle:Result:deleteDuplicateEntry

bs_result_add_team:
    path:    /Result/Add/Team
    defaults:
        _controller:    BSResultBundle:Result:addTeam