bs_bet_home:
    path:    /Bet/Home
    defaults:
        _controller:    BSBetBundle:Bet:home

bs_bet_result_update:
    path:    /Bet/Update
    defaults:
        _controller:    BSBetBundle:Bet:update