bs_bet_home:
    path:    /Bet/Get/{labelStrategy}
    defaults:
        _controller:    BSBetBundle:Bet:get

bs_bet_result_update:
    path:    /Bet/Update
    defaults:
        _controller:    BSBetBundle:Bet:update