<?php

namespace BS\TeamBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifyDuplicate($teamName)
    {
        $query = $this->_em->createQuery('SELECT t FROM BSTeamBundle:Team t WHERE t.name = :searchName');
        $query->setParameter('searchName', $teamName);
        return $query->getResult();
    }

    public function getIdByName($name){
        $query = $this->_em->createQuery('SELECT t.id FROM BSTeamBundle:Team t WHERE t.name = :name');
        $query->setParameter('name', $name);
        return $query->getResult();
    }
}
