<?php

namespace BS\TeamBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifyDuplicate($teamName, $competitionId)
    {
        $query = $this->_em->createQuery('SELECT t FROM BSTeamBundle:Team t WHERE t.name = :teamName AND t.competitionId = :competitionId');
        $query->setParameters(Array('teamName' => $teamName, 'competitionId' => $competitionId));
        return $query->getResult();
    }

    public function getIdByName($name){
        $query = $this->_em->createQuery('SELECT t.id FROM BSTeamBundle:Team t WHERE t.name = :name');
        $query->setParameter('name', $name);
        return $query->getResult();
    }

    public function getTeamByCompetition($competitionId, $teamId){
        $query = $this->_em->createQuery('SELECT t FROM BSTeamBundle:Team t WHERE t.competitionId = :competitionId AND t.id = :teamId');
        $query->setParameters(Array('competitionId' => $competitionId, 'teamId' => $teamId));
        return $query->getResult();
    }

}
