<?php

namespace BS\BetBundle\Repository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifyDuplicate($outcome) //indexOffer et eventId
    {
        $query = $this->_em->createQuery('SELECT b FROM BSBetBundle:Bet b WHERE b.outcome = :outcome');
        $query->setParameter('outcome', $outcome);

        return $query->getResult();
    }
}
