<?php

namespace BS\BetBundle\Repository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifyDuplicate($outcome, $strategy) //indexOffer et eventId
    {
        $query = $this->_em->createQuery('SELECT b FROM BSBetBundle:Bet b WHERE b.outcome = :outcome AND b.strategy = :strategy');
        $query->setParameters(array('outcome' => $outcome, 'strategy' => $strategy));

        return $query->getResult();
    }

    public function getAllByStrategy($strategy)
    {

        $query = $this->_em->createQuery('SELECT b FROM BSBetBundle:Bet b WHERE b.strategy = :strategy');
        $query->setParameter('strategy', $strategy);

        return $query->getResult();
    }

    public function getAllForUpdate()
    {
        $query = $this->_em->createQuery('SELECT b FROM BSBetBundle:Bet b WHERE b.marketResult IS NULL');

        return $query->getResult();
    }
}
