bs_offer_get:
    path:    /Offer/Get
    defaults:
        _controller:    BSOfferBundle:Offer:get

bs_offer_delete_duplicate_offer:
    path:    /Offer/Delete/Duplicate
    defaults:
        _controller:    BSOfferBundle:Offer:deleteDuplicateEntry

bs_outcome_update_label:
    path:    /Outcome/Update
    defaults:
        _controller:    BSOfferBundle:Offer:updateLabel

bs_offer_update_home_outside:
    path:    /Offer/Update
    defaults:
        _controller:    BSOfferBundle:Offer:updateHomeOutside

bs_result_update:
    path:    /Result/Update
    defaults:
        _controller:    BSResultBundle:Result:updateResult