bs_offer_get:
    path:    /Offer/Get
    defaults:
        _controller:    BSOfferBundle:Offer:get

bs_offer_delete_duplicate_offer:
    path:    /Offer/Delete/Duplicate
    defaults:
        _controller:    BSOfferBundle:Offer:deleteDuplicateEntry