<?php

namespace BS\ResultBundle\Repository;

/**
 * MarketResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketResultRepository extends \Doctrine\ORM\EntityRepository
{
}
