<?php

namespace BS\ResultBundle\Repository;

/**
 * MarketResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketResultRepository extends \Doctrine\ORM\EntityRepository
{

    public function verifyDuplicate($marketResult, $result)
    {
        $query = $this->_em->createQuery('SELECT m FROM BSResultBundle:MarketResult m WHERE m.indexMarketResult = :indexMarketResult AND m.eventId = :eventId');
        $query->setParameters(array('eventId' => $result->eventId, 'indexMarketResult' => $marketResult->index));
        return $query->getResult();
    }
}
