<?php

namespace BS\ResultBundle\Repository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResultByEventId($eventId)
    {
        $query = $this->_em->createQuery('SELECT r FROM BSResultBundle:Result r WHERE r.eventId = :eventId');
        $query->setParameter('eventId',$eventId);

        return $query->getResult();
    }

    public function verifyDuplicate($result)
    {
        $query = $this->_em->createQuery('SELECT r FROM BSResultBundle:Result r WHERE r.eventId = :eventId');
        $query->setParameter('eventId', $result->eventId);

        return $query->getResult();
    }

    public function getAllResult()
    {
        $query = $this->_em->createQuery('SELECT r FROM BSResultBundle:Result r');
        return $query->getResult();
    }

    public function getResultByTeamId($teamId)
    {
        $query = $this->_em->createQuery('SELECT r FROM BSResultBundle:Result r WHERE r.homeTeamId = :id OR r.outsideTeamId = :id');
        $query->setParameter('id',$teamId);
        return $query->getResult();
    }


}
