<?php

namespace BS\ResultBundle\Repository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBySportIdAndStrategy($sportId, $strategy)
    {
        $query = $this->_em->createQuery('SELECT s FROM BSResultBundle:Sport s WHERE s.sportId = :sportId AND s.strategy = :strategy');
        $query->setParameters(array('sportId' => $sportId, 'strategy' => $strategy));

        return $query->getResult();
    }
}
