<?php

namespace BS\ResultBundle\Repository;

/**
 * StrategyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrategyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByLabel($labelStrategy)
    {
        $query = $this->_em->createQuery('SELECT s FROM BSResultBundle:Strategy s WHERE s.labelStrategy = :labelStrategy');
        $query->setParameter('labelStrategy', $labelStrategy);

        return $query->getResult();
    }

    public function getPositive()
    {
        $query = $this->_em->createQuery('SELECT s FROM BSResultBundle:Strategy s WHERE s.returnOnInvestment >= 1');

        return $query->getResult();
    }
}
